-- 各種テーブル削除
DROP TABLE IF EXISTS order_details;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS categories;

-- カテゴリーテーブル
CREATE TABLE categories(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50)
);

-- 商品テーブル
CREATE TABLE items(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER REFERENCES categories(id),
    name VARCHAR(255),
    price INTEGER CHECK(price >= 0)
);

-- 顧客テーブル
CREATE TABLE customers(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    address VARCHAR(255),
    tel VARCHAR(20),
    email VARCHAR(255) UNIQUE
);

-- 注文テーブル
CREATE TABLE orders(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER REFERENCES customers(id),
    ordered_on DATE DEFAULT CURRENT_DATE,
    total_price INTEGER
);

-- 注文明細テーブル
CREATE TABLE order_details(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INTEGER REFERENCES orders(id),
    item_id INTEGER REFERENCES items(id),
    quantity INTEGER CHECK(quantity > 0)
);